# More Advanced Topic with NumPy
## Array Dimensions and Array Broadcasting
Now that we are more familiar with **attributes**. Let's import NumPy as it is usually imported in practice.

In [1]:
import numpy as np

The syntax of `from XXX import *` is hardly used in practice, because of **namespace polution**.


### Getting Higher-Dimensional Arrays with `reshape`
You can use `reshape` to obtain higher-dimensional arrays.

In [2]:
a = np.arange(12)

You can obtain the dimensions of an array using the `shape` attribute. Note that `shape` is not a function.

In [3]:
a.shape

(12,)

You can change the dimensions of an array using the `reshape` method, which is a function.

In [4]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Note the correct way for matrix multiplication.

In [7]:
a.reshape(3, 4).dot(a.reshape(4, 3)).shape

(3, 3)

or

In [8]:
(a.reshape(4, 3) @ a.reshape(3, 4)).shape

(4, 4)

### Other Ways of Constructing High-Dimensional Arrays

In [9]:
# from data
np.array([2.4, 2024, 3.14])

array([   2.4 , 2024.  ,    3.14])

In [10]:
# random array
np.random.random((2, 3))

array([[0.61991616, 0.31289166, 0.64646182],
       [0.91627658, 0.44863674, 0.0252059 ]])

In [11]:
# uniform array
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# diagonal matrix
np.diag(np.arange(3))

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

### Broadcasting Operations Between Higher-Dimensional Arrays

![broadcast](./fig/broadcast.png)

In [13]:
a = np.arange(0, 40, 10).reshape(4, 1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [14]:
b = np.arange(3).reshape(1, 3)
b

array([[0, 1, 2]])

In [15]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [16]:
a * b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

Broadcasting operations between higher-dimensional arrays can be a bit tricky to understand, but they are very versatile in practice.

**Example 1: Perceived temperature**

A geologist is analyzing the perceived temperature data for different cities.
Suppose one day, the average temperature in Harbin, Beijing, Shanghai, and Shenzhen is 0, 10, 20, and 30 °C respectively.

The perceived temperature is affected by humidity. Low, moderate, and high humidity will add 0, 1, and 2 °C to the perceived temperature respectively.

Then, all possible perceived temperatures for all four cities can be computed conveniently through `a + b`.

**Example 2: Solar panel**

A solar power plant is analyzing the energy output of four different solar panel arrays over three time periods of the day.

There are four types of solar panels: small rooftop installations, medium ground-mounted systems, large commercial installations, and utility-scale solar farms.

The base energy output is 0 (negligible), 10, 20, and 30 kWh respectively.

In different periods of the day, the based energy output must be multiplied by a factor. In the evening, morning, and afternoon, the multiplier is 0, 1, and 2, respectively.

Then, all possible energy output can be computed conveniently by `a * b`.

## Array Manipulation
### Indexing and Slicing
Use `[]` to extract an element or elements from an array

In [17]:
a = np.linspace(0, 1, 11)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
a[1]

np.float64(0.1)

In [19]:
a[1:3]

array([0.1, 0.2])

In [20]:
a = np.random.random((3, 3))
a

array([[0.12809484, 0.71091249, 0.15131048],
       [0.79576521, 0.31530369, 0.79733531],
       [0.54479969, 0.49699885, 0.92812315]])

In [21]:
# the first row
a[0]

array([0.12809484, 0.71091249, 0.15131048])

In [22]:
a[0, 2]

np.float64(0.15131048103051525)

In [23]:
a[0][2]

np.float64(0.15131048103051525)

In [24]:
# the second column
a[:, 1]

array([0.71091249, 0.31530369, 0.49699885])

In [25]:
# the last two rows
a[1:3]

array([[0.79576521, 0.31530369, 0.79733531],
       [0.54479969, 0.49699885, 0.92812315]])

In [26]:
# the first two columns
a[:, :2]

array([[0.12809484, 0.71091249],
       [0.79576521, 0.31530369],
       [0.54479969, 0.49699885]])

In [27]:
a = np.random.random((2, 3, 4))
a

array([[[0.83435283, 0.41886607, 0.69328268, 0.14525135],
        [0.15851859, 0.71192071, 0.90454291, 0.53380998],
        [0.04841791, 0.23016852, 0.01603492, 0.12371295]],

       [[0.50026208, 0.94386427, 0.71407761, 0.63392175],
        [0.00946301, 0.91336642, 0.38351117, 0.32573043],
        [0.08366165, 0.2936661 , 0.87704289, 0.81406503]]])

In [28]:
a[0, 1, 2]

np.float64(0.9045429084638394)

In [29]:
a[:, 0, :]

array([[0.83435283, 0.41886607, 0.69328268, 0.14525135],
       [0.50026208, 0.94386427, 0.71407761, 0.63392175]])

### Other Operations
Matrix transpose, setting elements, iteration over rows, stacking, copying......