# More Advanced Topic with NumPy
## Array Dimensions and Array Broadcasting
Now that we are more familiar with **attributes**. Let's import NumPy as it is usually imported in practice.

In [1]:
import numpy as np

The syntax of `from XXX import *` is hardly used in practice, because of **namespace polution**.


### Getting Higher-Dimensional Arrays with `reshape`
You can use `reshape` to obtain higher-dimensional arrays.

In [2]:
a = np.arange(12)

You can obtain the dimensions of an array using the `shape` attribute. Note that `shape` is not a function.

In [3]:
a.shape

(12,)

You can change the dimensions of an array using the `reshape` method, which is a function.

In [4]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
a.reshape(3, 4).dot(a.reshape(4,3)).shape

(3, 3)

### Other Ways of Constructing High-Dimensional Arrays

In [8]:
# random array
np.random.random((2, 3))

array([[0.26930555, 0.95196142, 0.41734752],
       [0.89453172, 0.73347827, 0.7115399 ]])

In [9]:
# uniform array
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# diagonal matrix
np.diag(np.arange(3))

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

### Broadcasting Operations Between Higher-Dimensional Arrays

![broadcast](./fig/broadcast.png)

In [11]:
a = np.arange(0, 40, 10).reshape(4, 1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [12]:
b = np.arange(3).reshape(1, 3)
b

array([[0, 1, 2]])

In [13]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [14]:
a * b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

Broadcasting operations between higher-dimensional arrays can be a bit tricky to understand, but they are very versatile in practice.

**Example 1: Perceived temperature**

A geologist is analyzing the perceived temperature data for different cities.
Suppose one day, the average temperature in Harbin, Beijing, Shanghai, and Shenzhen is 30, 20, 10, and 0 °C respectively.

The perceived temperature is affected by humidity. Low, moderate, and high humidity will add 0, 1, and 2 °C to the perceived temperature respectively.

Then, all possible perceived temperatures for all four cities can be computed conveniently through `a + b`.

**Example 2: Solar panel**

A solar power plant is analyzing the energy output of four different solar panel arrays over three time periods of the day.

There are four types of solar panels: small rooftop installations, medium ground-mounted systems, large commercial installations, and utility-scale solar farms.

The base energy output is 0 (negligible), 10, 20, and 30 kWh respectively.

In different periods of the day, the based energy output must be multiplied by a factor. In the evening, morning, and afternoon, the multiplier is 0, 1, and 2, respectively.

Then, all possible energy output can be computed conveniently by `a * b`.

## Array Manipulation
### Indexing and Slicing
Use `[]` to extract an element or elements from an array

In [15]:
a = np.linspace(0, 1, 11)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
a[1]

np.float64(0.1)

In [17]:
a[1:3]

array([0.1, 0.2])

In [18]:
a = np.random.random((3, 3))
a

array([[0.65118143, 0.25009134, 0.40627808],
       [0.09767163, 0.30154275, 0.50839077],
       [0.85788753, 0.22566815, 0.64851313]])

In [19]:
# the first row
a[0]

array([0.65118143, 0.25009134, 0.40627808])

In [20]:
a[0, 2]

np.float64(0.4062780827025373)

In [21]:
a[0][2]

np.float64(0.4062780827025373)

In [22]:
# the second column
a[:, 1]

array([0.25009134, 0.30154275, 0.22566815])

In [23]:
# the last two rows
a[1:3]

array([[0.09767163, 0.30154275, 0.50839077],
       [0.85788753, 0.22566815, 0.64851313]])

In [24]:
# the first two columns
a[:, :2]

array([[0.65118143, 0.25009134],
       [0.09767163, 0.30154275],
       [0.85788753, 0.22566815]])

In [25]:
a = np.random.random((2, 3, 4))
a

array([[[0.94445158, 0.43631716, 0.81380423, 0.53075759],
        [0.37022136, 0.86052745, 0.77605137, 0.64277831],
        [0.77490859, 0.20748048, 0.16944701, 0.7733969 ]],

       [[0.13386501, 0.93551905, 0.07529527, 0.89240139],
        [0.27061062, 0.76426383, 0.50120847, 0.71187314],
        [0.33083309, 0.78820802, 0.81239641, 0.61372201]]])

In [26]:
a[0, 1, 2]

np.float64(0.7760513731418605)

In [27]:
a[:, 0, :]

array([[0.94445158, 0.43631716, 0.81380423, 0.53075759],
       [0.13386501, 0.93551905, 0.07529527, 0.89240139]])