## Basics of Python and Jupyter Notebook

## What is Python? Why Use Python for Mathematical Modeling?

Python is a programming language that is both easy to learn and powerful. 
In recent years, with the rapid development of artificial intelligence, Python has emerged as the preferred language for AI development.

Mathematical modeling doesn’t necessarily require Python, nor does it always require programming. 
You can accomplish some tasks using Excel, which we will demonstrate later. 
MATLAB is also a popular tool for mathematical modeling.
So, why use Python for mathematical modeling? Here are a few reasons:

- Python can be integrated with Jupyter Notebook, allowing the combination of text, formulas, code, and charts for optimal teaching outcomes. By using Binder, you can skip the installation process and start working on experiments directly in your web browser.
- Python is simple and easy to learn, making it accessible even for students with no programming background. Many can get started in just 20 minutes.
- Python is a very popular language with numerous projects developed in it. This allows you to accomplish many tasks with just a few lines of code. After learning the basics of Python, students can independently search for resources and write a basic "convolutional neural network" for recognizing handwritten digits with just 20 lines of code. You might be surprised at what Python can do.

Although Python also supports symbolic computation (similar to Mathematica and Maple), in this course, we will primarily focus on numerical computation. While symbolic computation can be more efficient in principle, numerical computation has broader applications.

Python isn’t perfect and does have some limitations for this course. For example, Python is a general-purpose programming language and follows programming conventions, which means its support for some mathematical expressions is limited. For instance, you can’t write 2x to represent 2 times $x$, and exponentiation must be written as 2**3.

## What is Jupyter Notebook?
Jupyter Notebook is an "interactive environment." As the name suggests, you can think of it as a digital notebook.

A notebook is made up of many cells, and each cell contains code and its output. Cells are the units of code execution. In the experiments that follow, we will execute the code one cell at a time and observe the outputs.

## What are we doing today?
- A 20-minute introduction to Python and Jupyter Notebook for complete beginners.


## 1. A 20-Minute Introduction to Python and Jupyter Notebook

### Running Simple Code
In the next cell, we will run a very simple line of code: 1+1, and then observe the output.

The general way to execute code is: click on the cell with your mouse, or use the up and down arrow keys to select the cell, and then press Shift + Enter.

Alternatively, use the run button in the toolbar.

In [1]:
1+1

2

In this cell, we executed a standard Python line of code, and we observed that Python provided a reliable result. Each executed cell is assigned an ID, which appears next to the code and output. This ID increments with each execution, though we generally don't need to worry about it.

Try modifying this cell to perform subtraction, multiplication, division, exponentiation, and mixed operations.

To edit a cell, you need to enter the cell's editing environment. There are two ways to do this: first, you can click within the code area with your mouse; second, you can select the cell by clicking the blank space in the left and then press Enter. 

If you accidentally enter the editing environment for these instructions (instead of the code), simply press Shift + Enter to revert it to its original state.

Explore how Python + Jupyter Notebook can function as a calculator.

### Who is Performing These Calculations?
Our calculations are running on Binder's servers, not on your computer or mine. If there are any issues with the network connection, these calculations will not be able to proceed. When the network is unstable, you may need to refresh the page.

**If you return to this page after a long time, your results will lost and can not be recovered.**

Alternatively, you may open the notebook with Anaconda, and perform these computations on your local machine. Then there will be no network issue and your notebook will be permanently saved.

### Variable Assignment
In Python, we can assign values to a symbol and store it for future use. This symbol is called a **variable**. Variable assignment does not produce any output.

In [2]:
pi = 3.1415926535

By directly running this variable in a cell, you can retrieve its value.

In [3]:
pi

3.1415926535

In [4]:
pi * pi

9.869604400525171

Try changing the value of pi!

### Multiple Statements in a Single Cell
A single cell can execute multiple statements at once. To write multiple lines of code in a cell, simply press Enter to start a new line within the cell.

In [5]:
pi2 = pi * pi
pi2 / pi

3.1415926535

### An Exception Occurred!
When you attempt to do something that Python doesn't allow, an **"exception"** occurs. Encountering exceptions is perfectly normal. Generally, by analyzing the error message provided by the exception, you can identify and resolve the issue.

In [6]:
1 / 0

ZeroDivisionError: division by zero

Note that Chinese characters cannot replace English characters. In computer experiments, it's generally best to avoid typing in Chinese. It's recommended to switch your input method to English.

In [7]:
3。14

SyntaxError: invalid decimal literal (1996689795.py, line 1)

In [8]:
blablabksldjfiawejfhiuwfhjwiuefbiwoaijiegouhuaxuehahaha

NameError: name 'blablabksldjfiawejfhiuwfhjwiuefbiwoaijiegouhuaxuehahaha' is not defined

In [9]:
sin(pi)

NameError: name 'sin' is not defined

If you encounter an exception that you cannot resolve during the study, please contact the TAs.

### Some Magic (Importing Packages)
We previously saw that directly calculating sin(pi) failed because sin is not a recognized variable; Python doesn’t know what sin is. Next, we will import some packages to enable us to perform useful mathematical operations.

You don’t need to worry about the details of this importing process.
If you are interested, you're encouraged to ask the TAs about it in the tutorials.

In [10]:
from numpy import *
from matplotlib.pyplot import plot

In [11]:
sin(pi)

np.float64(1.2246467991473532e-16)

A term like `sin` followed by parentheses can be **called**, and the term a function. The variables inside the parentheses are referred to as parameters.

### Arrays and Attributes (.)
Why do we need arrays? It's time for an Excel demonstration!

In [12]:
arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a = arange(11)

Many variables in Python have **attributes**, which can be accessed using a `.` (dot).

In [14]:
a.mean()

np.float64(5.0)

Arrays can perform element-wise addition, subtraction, multiplication, and division operations.

In [15]:
a * a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [16]:
a / a

/tmp/ipykernel_113345/3063000341.py:1: RuntimeWarning: invalid value encountered in divide
  a / a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

A warning may appear because of a `0/0` operation. However, since it's an array operation and many elements can still be divided, an error isn't raised.

`nan` stands for "not a number."

In [17]:
a.dot(a)

np.int64(385)

Be aware of the difference between element-wise multiplication (multiplying elements one by one) and dot product (multiplying elements one by one and then summing the results).

In [18]:
(a * a).sum()

np.int64(385)

Pay attention to the parentheses above. Attribute access has a very high priority in Python.

In [19]:
a * a.sum()

array([  0,  55, 110, 165, 220, 275, 330, 385, 440, 495, 550])

When you need more than just integers, you can use `linspace`. If a function has multiple parameters, separate them with commas `,`.

In [20]:
linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Summary: 20-Minute Introduction to Python and Jupyter Notebook
- Basic Syntax
  - Variable assignment: a = 1
  - Calling a function: sin(a)
  - Accessing attributes: a.real
- Notebook Operations
  - Editing and executing cells
  - Creating and deleting cells
- Array Operations
  - Creating linear arrays: arange(10), linspace(0, 49)
  - Addition, subtraction, multiplication, and division of arrays are generally element-wise operations

## todo: matplotlib

## Array Dimensions and Array Broadcasting
### Getting Higher-Dimensional Arrays with `reshape`
You can use `reshape` to obtain higher-dimensional arrays.

In [21]:
a = arange(12)

You can obtain the dimensions of an array using the `shape` attribute. Note that `shape` is not a function.

In [22]:
a.shape

(12,)

You can change the dimensions of an array using the `reshape` method.

In [23]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
a.reshape(3, 4).dot(a.reshape(4,3)).shape

(3, 3)

### Broadcasting Operations Between Higher-Dimensional Arrays

![broadcast](./fig/broadcast.png)

In [27]:
a = arange(0, 40, 10).reshape(4, 1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [28]:
b = arange(3).reshape(1, 3)

In [29]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [30]:
a * b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

Broadcasting operations between higher-dimensional arrays can be a bit tricky to understand, but they are very versatile in practice.